image: node:10.15.0
pipelines:
    default:
        - step:
              name: Build & Unit Testing
              script:
                  - npm install
                  - npm install -g gulp
                  - gulp compile
                  - npm test
        - step:
              name: Create Artifact
              script:
                  - npm install
                  - npm install -g gulp
                  - gulp compile
                  - tar -cvzf application.tgz lib/ package-lock.json package.json .env permissions.json
              artifacts:
                  - application.tgz
        - step:
              name: Deploy to production
              deployment: production
              script:
                  - pipe: atlassian/heroku-deploy:0.1.1
                    variables:
                        HEROKU_API_KEY: $HEROKU_API_KEY
                        HEROKU_APP_NAME: $HEROKU_APP_NAME
                        ZIP_FILE: "application.tgz"
